name: Collaboration Ready Checklist
description: Use this form to ensure your repository is collaboration-ready
title: "[Checklist]: "
labels: ["checklist"]
body:
- type: markdown
  attributes:
    value: "## Repository Settings"
- type: checkboxes
  id: repo-settings
  attributes:
    label: "Repository Settings"
    options:
      - label: "Set appropriate repository visibility (public or private)"
        description: "[Learn more](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-repository-settings#about-repository-visibility)"
      - label: "Configure branch protection rules"
        description: "[Learn more](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches)"
- type: markdown
  attributes:
    value: "## Repository Contents"
- type: checkboxes
  id: repo-contents
  attributes:
    label: "Repository Contents"
    options:
      - label: "Create an informative README.md"
        description: "[Learn more](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes)"
      - label: "Add a LICENSE.md file"
        description: "[Learn more](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)"
      - label: "Include CONTRIBUTING.md"
        description: "[Learn more](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)"
      - label: "Set up CODEOWNERS"
        description: "[Learn more](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)"
      - label: "Establish a CODE_OF_CONDUCT.md"
        description: "[Learn more](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project)"
- type: input
  id: license
  attributes:
    label: "Which license did you choose? (Please specify)"
    placeholder: "Enter the license name here"
- type: markdown
  attributes:
    value: "## Automation/Checks"
- type: checkboxes
  id: automation-checks
  attributes:
    label: "Automation/Checks"
    options:
      - label: "Implement code linting"
        description: "[Learn more](https://github.com/marketplace/actions/super-linter)"
      - label: "Set up tests / Continuous Integration (CI)"
        description: "[Learn more](https://docs.github.com/en/actions/guides/about-continuous-integration)"
      - label: "Configure status checks"
        description: "[Learn more](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-status-checks)"
      - label: "Consider Continuous Deployment (CD)"
        description: "[Learn more](https://docs.github.com/en/actions/guides/about-continuous-deployment)"
- type: markdown
  attributes:
    value: "## Security"
- type: checkboxes
  id: security
  attributes:
    label: "Security"
    options:
      - label: "Assign appropriate roles/permissions"
        description: "[Learn more](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization)"
      - label: "Manage secrets securely"
        description: "[Learn more](https://docs.github.com/en/actions/security-guides/encrypted-secrets)"
      - label: "Set up scanners for dependencies, secrets, general vulnerabilities"
        description: "[Learn more](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates)"
      - label: "Consider Dependabot version updates"
        description: "[Learn more](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates)"
      - label: "Provide a SECURITY.md & enable Private Vulnerability Reporting"
        description: "[Learn more](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository)"