name: Collaboration Ready Checklist
description: Use this form to ensure your repository is collaboration-ready
title: "Is this repository collaboration-ready?"
labels: []
body:
- type: markdown
  attributes:
    value: "## Repository Settings"
- type: checkboxes
  id: repo-settings
  attributes:
    label: "Repository Settings"
    description: >
      Ensure the repository settings are correctly configured.
      [Learn more about repository settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-repository-settings#about-repository-visibility)
      and [branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches)
    options:
      - label: "Set appropriate repository visibility (public or private)"
      - label: "Configure branch protection rules"
- type: markdown
  attributes:
    value: "## Repository Contents"
- type: checkboxes
  id: repo-contents
  attributes:
    label: "Repository Contents"
    description: >
      Ensure the repository contains all the necessary files.
      [Learn more about README](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes),
      [LICENSE](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository),
      [CONTRIBUTING](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors),
      [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners),
      and [CODE_OF_CONDUCT](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project)
    options:
      - label: "Create an informative README.md"
      - label: "Add a LICENSE.md file"
      - label: "Include CONTRIBUTING.md"
      - label: "Set up CODEOWNERS"
      - label: "Establish a CODE_OF_CONDUCT.md"
- type: input
  id: license
  attributes:
    label: "Which license did you choose? (Please specify)"
    placeholder: "Enter the license name here"
- type: markdown
  attributes:
    value: "## Automation/Checks"
- type: checkboxes
  id: automation-checks
  attributes:
    label: "Automation/Checks"
    description: >
      Ensure the repository has the necessary automation and checks in place.
      [Learn more about code linting](https://github.com/marketplace/actions/super-linter),
      [CI](https://docs.github.com/en/actions/guides/about-continuous-integration),
      and [status checks](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-status-checks)
    options:
      - label: "Implement code linting"
      - label: "Set up tests / Continuous Integration (CI)"
      - label: "Configure status checks"
      - label: "Consider Continuous Deployment (CD)"
- type: markdown
  attributes:
    value: "## Security"
- type: checkboxes
  id: security
  attributes:
    label: "Security"
    description: >
      Ensure the repository has the necessary security measures in place.
      [Learn more about roles/permissions](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization),
      [managing secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets),
      [scanners](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates),
      and [security policies](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository)
    options:
      - label: "Assign appropriate roles/permissions"
      - label: "Manage secrets securely"
      - label: "Set up scanners for dependencies, secrets, general vulnerabilities"
      - label: "Consider Dependabot version updates"
      - label: "Provide a SECURITY.md & enable Private Vulnerability Reporting"