name: Collaboration Ready Checklist
description: Use this form to ensure your repository is collaboration-ready
title: "Is this repository collaboration-ready?"
labels: []
body:
- type: markdown
  attributes:
    value: "Read more about [collaboration-ready repositories on the GitHub Blog](https://github.blog/2023-08-04-a-checklist-and-guide-to-get-your-repository-collaboration-ready/)!"
- type: checkboxes
  id: repo-settings
  attributes:
    label: "Repository Settings"
    description: |-
      Ensure the repository settings are correctly configured.      
      Learn more about [repository settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features)
      and [branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches)
    options:
      - label: "Set appropriate repository visibility (public or private)"
      - label: "Configure branch protection rules"
- type: input
  id: notes-repo-settings
  attributes:
    label: "Notes:"
    placeholder: "Enter any notes here. For example, any additional settings that were configured, or any issues encountered during configuration."
- type: checkboxes
  id: repo-contents
  attributes:
    label: "Repository Contents"
    description: |-
      Ensure the repository contains all the necessary files.      
      Learn more about [READMEs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes),
      [LICENSE](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository),
      [CONTRIBUTING](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors),
      [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners),
      and [CODE_OF_CONDUCT](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project)
    options:
      - label: "Create an informative README.md"
      - label: "Add a LICENSE file"
      - label: "Include CONTRIBUTING.md"
      - label: "Set up CODEOWNERS"
      - label: "Establish a CODE_OF_CONDUCT.md"
- type: input
  id: notes-repo-contents
  attributes:
    label: "Notes:"
    placeholder: "Enter any notes here. For example, which files did you choose not to include (and why)?"
- type: input
  id: license
  attributes:
    label: "Which license did you choose? (Please specify)"
    placeholder: "Enter the license name here"
- type: checkboxes
  id: automation-checks
  attributes:
    label: "Automation/Checks"
    description: |-
      Ensure the repository has the necessary automation and checks in place.      
      Learn more about [code linting](https://github.blog/2020-06-18-introducing-github-super-linter-one-linter-to-rule-them-all/),
      [CI](https://docs.github.com/en/actions/guides/about-continuous-integration),
      and [status checks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks)
    options:
      - label: "Implement code linting"
      - label: "Set up tests / Continuous Integration (CI)"
      - label: "Configure status checks"
      - label: "Consider Continuous Deployment (CD)"
- type: input
  id: notes-automation-checks
  attributes:
    label: "Notes:"
    placeholder: "Enter any notes here. For example, any issues encountered during the implementation of automation or checks."
- type: checkboxes
  id: security
  attributes:
    label: "Security"
    description: |-
      Ensure the repository has the necessary security measures in place.      
      Learn more about [roles/permissions](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization),
      [managing secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets),
      [dependency scanning](https://docs.github.com/en/code-security/dependabot),
      and [security policies](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository)
    options:
      - label: "Assign appropriate roles/permissions"
      - label: "Manage secrets securely"
      - label: "Set up scanners for dependencies, secrets, general vulnerabilities"
      - label: "Consider Dependabot version updates"
      - label: "Provide a SECURITY.md & enable Private Vulnerability Reporting"
- type: input
  id: notes-security
  attributes:
    label: "Notes:"
    placeholder: "Enter any notes here. For example, any additional security measures implemented or any issues encountered during implementation."
- type: checkboxes
  id: advanced-options
  attributes:
    label: "Advanced Options"
    description: |-
      Additional options to consider for your repository.      
      Learn more about [issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository),
      [GitHub Codespaces](https://docs.github.com/en/codespaces/setting-up-your-codespace/configuring-codespaces-for-your-project),
      and [environments](https://docs.github.com/en/actions/deployment/about-environments)
    options:
      - label: "Add Issue Templates"
      - label: "Configure GitHub Codespaces"
      - label: "Define Environments"
- type: input
  id: notes-advanced-options
  attributes:
    label: "Notes:"
    placeholder: "Enter any notes here. For example, any additional options implemented or any issues encountered during implementation."
- type: checkboxes
  id: next-steps
  attributes:
    label: "Next Steps / Externalities"
    description: |-
      Additional steps to take to promote your repository and engage with your community.      
      Learn more about [labels](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/encouraging-helpful-contributions-to-your-project-with-labels),
      [GitHub Projects and Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues),
      [repository promotion](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/displaying-a-sponsor-button-in-your-repository),
      and [community building](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/building-a-strong-community)
    options:
      - label: "Commit to being responsive"
      - label: "Use GitHub Projects and Issues for project management"
      - label: "Promote your project for visibility"
      - label: "Engage with your community"
- type: input
  id: notes-next-steps
  attributes:
    label: "Notes:"
    placeholder: "Enter any notes here. For example, any additional steps taken or any issues encountered during implementation."